@startuml

title Diagrama de Secuencia: Creación e inicialización de la interfaz gráfica del juego

actor Usuario

participant "VistaMapa" as Vista
participant "Juego" as Juego
participant "TableroGridpane" as Tablero
participant "Sprites" as Sprites

activate Usuario
Usuario -> Vista: Inicia la aplicación

Vista -> Juego: Crea un nuevo juego
activate Juego
Juego -> Sprites: Carga sprites
activate Sprites
Sprites --> Juego: Sprites cargados
deactivate Sprites
Juego -> Vista: Juego creado

Vista -> Tablero: Inicializa tablero
activate Tablero
Tablero --> Vista: Tablero inicializado
Vista -> Tablero: Configura celdas y elementos
Tablero --> Vista: Celdas y elementos configurados
deactivate Tablero

Vista -> Vista: Asigna eventos de teclado y mouse
Vista -> Vista: Espera interacción del usuario

@enduml